<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExercisesTable3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exercices = [

            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '901', 'slug' => 'problemas-de-planteo-de-punto-de-equilibrio-9', 'active' => 'yes', 'order' => '9'],

            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '902', 'slug' => 'logica-proposiciones-simples-8', 'active' => 'yes', 'order' => '8'],

            ['item_id' => '903', 'slug' => 'propiedades-de-reduccion-y-simplificacion-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '903', 'slug' => 'propiedades-de-reduccion-y-simplificacion-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '903', 'slug' => 'propiedades-de-reduccion-y-simplificacion-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '903', 'slug' => 'propiedades-de-reduccion-y-simplificacion-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '903', 'slug' => 'propiedades-de-reduccion-y-simplificacion-5', 'active' => 'yes', 'order' => '5'],

            ['item_id' => '904', 'slug' => 'conjuntos-familia-de-conjuntos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '904', 'slug' => 'conjuntos-familia-de-conjuntos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '904', 'slug' => 'conjuntos-familia-de-conjuntos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '904', 'slug' => 'conjuntos-familia-de-conjuntos-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '905', 'slug' => 'conjuntos-aplicaciones-2-conjuntos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '905', 'slug' => 'conjuntos-aplicaciones-2-conjuntos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '905', 'slug' => 'conjuntos-aplicaciones-2-conjuntos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '905', 'slug' => 'conjuntos-aplicaciones-2-conjuntos-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '906', 'slug' => 'conjuntos-aplicaciones-3-conjuntos-14', 'active' => 'yes', 'order' => '14'],

            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '907', 'slug' => 'induccion-matematica-induccion-con-simbolo-sumatorio-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '908', 'slug' => 'induccion-matematica-otros-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '908', 'slug' => 'induccion-matematica-otros-2', 'active' => 'yes', 'order' => '2'],

            ['item_id' => '909', 'slug' => 'sumatorias-sumatorias-basicas-1', 'active' => 'yes', 'order' => '1'],

            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '910', 'slug' => 'sumatorias-otros-prop-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '911', 'slug' => 'sumatorias-exponencial-logaritmica-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '911', 'slug' => 'sumatorias-exponencial-logaritmica-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '911', 'slug' => 'sumatorias-exponencial-logaritmica-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '911', 'slug' => 'sumatorias-exponencial-logaritmica-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '912', 'slug' => 'sumatorias-teorema-del-binomio-6', 'active' => 'yes', 'order' => '6'],

            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '913', 'slug' => 'sumatorias-demostraciones-prop-estadistica-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '914', 'slug' => 'teo-del-binomio-num-factorial-desarrollo-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '915', 'slug' => 'teo-del-binomio-num-factorial-un-termino-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '915', 'slug' => 'teo-del-binomio-num-factorial-un-termino-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '915', 'slug' => 'teo-del-binomio-num-factorial-un-termino-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '915', 'slug' => 'teo-del-binomio-num-factorial-un-termino-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '916', 'slug' => 'teo-del-binomio-num-factorial-term-central-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '916', 'slug' => 'teo-del-binomio-num-factorial-term-central-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '916', 'slug' => 'teo-del-binomio-num-factorial-term-central-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '916', 'slug' => 'teo-del-binomio-num-factorial-term-central-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '916', 'slug' => 'teo-del-binomio-num-factorial-term-central-5', 'active' => 'yes', 'order' => '5'],

            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '917', 'slug' => 'teo-del-binomio-num-factorial-term-condicionado-8', 'active' => 'yes', 'order' => '8'],

            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '918', 'slug' => 'teo-del-binomio-num-factorial-coef-7', 'active' => 'yes', 'order' => '7'],

            ['item_id' => '919', 'slug' => 'teo-del-binomio-num-factorial-indep-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '919', 'slug' => 'teo-del-binomio-num-factorial-indep-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '919', 'slug' => 'teo-del-binomio-num-factorial-indep-3', 'active' => 'yes', 'order' => '3'],

            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '920', 'slug' => 'geo-analitica-conicas-rectas-pto-pend-2-ptos-11', 'active' => 'yes', 'order' => '11'],

            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '921', 'slug' => 'geo-analitica-conicas-rectas-pto-mas-condicion-14', 'active' => 'yes', 'order' => '14'],

            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '922', 'slug' => 'geo-analitica-conicas-rectas-mas-nivel-13', 'active' => 'yes', 'order' => '13'],

            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '923', 'slug' => 'geo-analitica-conicas-rectas-parametros-7', 'active' => 'yes', 'order' => '7'],

            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '924', 'slug' => 'geo-analitica-conicas-circunferencia-normal-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '925', 'slug' => 'geo-analitica-conicas-circunferencia-mas-nivel-11', 'active' => 'yes', 'order' => '11'],

            ['item_id' => '926', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-circunferencia-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '926', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-circunferencia-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '926', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-circunferencia-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '926', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-circunferencia-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '927', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-parabola-9', 'active' => 'yes', 'order' => '9'],

            ['item_id' => '928', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-elipse-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '928', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-elipse-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '928', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-elipse-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '928', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-elipse-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '929', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-hiperbola-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '929', 'slug' => 'prob-apl-geo-analitica-aplicacion-de-hiperbola-2', 'active' => 'yes', 'order' => '2'],

            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '930', 'slug' => 'funciones-en-rxr-funciones-graficas-12', 'active' => 'yes', 'order' => '12'],

            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '931', 'slug' => 'funciones-en-rxr-dominio-normal-14', 'active' => 'yes', 'order' => '14'],

            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '932', 'slug' => 'funciones-en-rxr-dominio-mas-nivel-12', 'active' => 'yes', 'order' => '12'],

            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '933', 'slug' => 'funciones-en-rxr-recorrido-normal-17', 'active' => 'yes', 'order' => '17'],

            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '934', 'slug' => 'funciones-en-rxr-reccorido-mas-nivel-17', 'active' => 'yes', 'order' => '17'],

            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-18', 'active' => 'yes', 'order' => '18'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-19', 'active' => 'yes', 'order' => '19'],
            ['item_id' => '935', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-normal-20', 'active' => 'yes', 'order' => '20'],

            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '936', 'slug' => 'funciones-en-rxr-inyectiva-epiyectiva-biyectiva-e-inversa-analitica-mas-nivel-11', 'active' => 'yes', 'order' => '11'],

            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '937', 'slug' => 'funciones-en-rxr-compuesta-valoraciones-18', 'active' => 'yes', 'order' => '18'],

            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '938', 'slug' => 'funciones-en-rxr-compuesta-normal-7', 'active' => 'yes', 'order' => '7'],

            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '939', 'slug' => 'funciones-en-rxr-compuesta-mas-nivel-6', 'active' => 'yes', 'order' => '6'],

            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '940', 'slug' => 'funciones-en-rxr-funciones-pares-e-impares-descomponer-6', 'active' => 'yes', 'order' => '6'],

            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '941', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-1-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '942', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-2-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '943', 'slug' => 'otros-tipos-funciones-funciones-exponencial-logaritmo-tipo-3-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '944', 'slug' => 'otros-tipos-funciones-funciones-mezclas-1', 'active' => 'yes', 'order' => '1'],

            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-18', 'active' => 'yes', 'order' => '18'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-19', 'active' => 'yes', 'order' => '19'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-20', 'active' => 'yes', 'order' => '20'],
            ['item_id' => '945', 'slug' => 'apl-modelado-funciones-planteo-modelos-lineales-21', 'active' => 'yes', 'order' => '21'],

            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '946', 'slug' => 'apl-modelado-funciones-planteo-funciones-cuadraticas-parabola-maximos-minimos-6', 'active' => 'yes', 'order' => '6'],

            ['item_id' => '947', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-otras-no-usual-1', 'active' => 'yes', 'order' => '1'],

            ['item_id' => '948', 'slug' => 'apl-modelado-funciones-planteo-aplicacion-de-funciones-economia-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '948', 'slug' => 'apl-modelado-funciones-planteo-aplicacion-de-funciones-economia-mas-nivel-2', 'active' => 'yes', 'order' => '2'],

            ['item_id' => '949', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-vida-media-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '949', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-vida-media-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '949', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-vida-media-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '949', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-vida-media-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '949', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-vida-media-5', 'active' => 'yes', 'order' => '5'],

            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '950', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-poblacion-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '951', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-economicos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '951', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-economicos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '951', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-economicos-3', 'active' => 'yes', 'order' => '3'],

            ['item_id' => '952', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-otros-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '952', 'slug' => 'apl-modelado-funciones-planteo-modelos-funcion-dada-exp-log-otros-2', 'active' => 'yes', 'order' => '2'],

            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '953', 'slug' => 'exponencial-ecuaciones-exponenciales-mas-nivel-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-18', 'active' => 'yes', 'order' => '18'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-19', 'active' => 'yes', 'order' => '19'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-20', 'active' => 'yes', 'order' => '20'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-21', 'active' => 'yes', 'order' => '21'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-22', 'active' => 'yes', 'order' => '22'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-23', 'active' => 'yes', 'order' => '23'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-24', 'active' => 'yes', 'order' => '24'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-25', 'active' => 'yes', 'order' => '25'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-26', 'active' => 'yes', 'order' => '26'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-27', 'active' => 'yes', 'order' => '27'],
            ['item_id' => '954', 'slug' => 'exponencial-cal-desarr-log-numeric-28', 'active' => 'yes', 'order' => '28'],

            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '955', 'slug' => 'exponencial-cal-desarr-log-literal-17', 'active' => 'yes', 'order' => '17'],

            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '956', 'slug' => 'exponencial-ecuaciones-exp-se-aplica-log-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '957', 'slug' => 'exponencial-ecuaciones-log-simples-18', 'active' => 'yes', 'order' => '18'],

            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-15', 'active' => 'yes', 'order' => '15'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-16', 'active' => 'yes', 'order' => '16'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-17', 'active' => 'yes', 'order' => '17'],
            ['item_id' => '958', 'slug' => 'exponencial-ecuaciones-log-mas-nivel-18', 'active' => 'yes', 'order' => '18'],

            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '959', 'slug' => 'exponencial-ecuaciones-mixtas-9', 'active' => 'yes', 'order' => '9'],

            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '960', 'slug' => 'exponencial-inecuaciones-log-7', 'active' => 'yes', 'order' => '7'],

            ['item_id' => '961', 'slug' => 'exponencial-inecuaciones-mixtas-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '961', 'slug' => 'exponencial-inecuaciones-mixtas-2', 'active' => 'yes', 'order' => '2'],

            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '962', 'slug' => 'exponencial-sist-de-ecuaciones-mixtos-8', 'active' => 'yes', 'order' => '8'],

            ['item_id' => '963', 'slug' => 'exponencial-graficas-log-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '963', 'slug' => 'exponencial-graficas-log-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '963', 'slug' => 'exponencial-graficas-log-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '963', 'slug' => 'exponencial-graficas-log-4', 'active' => 'yes', 'order' => '4'],

            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '964', 'slug' => 'logaritmo-exp-log-demostrativos-otros-8', 'active' => 'yes', 'order' => '8'],

            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '965', 'slug' => 'logaritmo-exp-log-funciones-tipo1-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '966', 'slug' => 'logaritmo-exp-log-funciones-tipo2-10', 'active' => 'yes', 'order' => '10'],

            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-6', 'active' => 'yes', 'order' => '6'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-7', 'active' => 'yes', 'order' => '7'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-8', 'active' => 'yes', 'order' => '8'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-9', 'active' => 'yes', 'order' => '9'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-10', 'active' => 'yes', 'order' => '10'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-11', 'active' => 'yes', 'order' => '11'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-12', 'active' => 'yes', 'order' => '12'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-13', 'active' => 'yes', 'order' => '13'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-14', 'active' => 'yes', 'order' => '14'],
            ['item_id' => '967', 'slug' => 'logaritmo-exp-log-funciones-tipo3-15', 'active' => 'yes', 'order' => '15'],

            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '968', 'slug' => 'ec-inec-trigonometricas-ecuaciones-trigonometricas-mas-nivel-6', 'active' => 'yes', 'order' => '6'],

            ['item_id' => '969', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-1-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '969', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-1-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '969', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-1-3', 'active' => 'yes', 'order' => '3'],

            ['item_id' => '970', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-2-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '970', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-2-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '970', 'slug' => 'ec-inec-trigonometricas-otras-ecuaciones-tipo-2-3', 'active' => 'yes', 'order' => '3'],

            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-1', 'active' => 'yes', 'order' => '1'],
            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-2', 'active' => 'yes', 'order' => '2'],
            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-3', 'active' => 'yes', 'order' => '3'],
            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-4', 'active' => 'yes', 'order' => '4'],
            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-5', 'active' => 'yes', 'order' => '5'],
            ['item_id' => '972', 'slug' => 'otros-calculos-demostraciones-dem-identidades-trigonomet-usando-complex-6', 'active' => 'yes', 'order' => '6'],
        ];

        foreach ($exercices as $exerciseData) {
            $exercise = new Exercise($exerciseData);
            $exercise->save();
        }
    }
}
