<?php

namespace Database\Seeders\ExerciseUniversities;

use Illuminate\Database\Seeder;
use App\Models\ExerciseUniversity;
use Illuminate\Support\Facades\Log;

class ExerciseUniversitiesParentsSeeder extends Seeder
{

    public function run(): void
    {
        $data = [
            //GRUPO 1 SEPTIEMBRE 2024

            /*  ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-nr-1',                            'name' => 'Guía "Cálculo: Números Reales"', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-logica-y-conjuntos-2',       'name' => 'Guía "Complementos: Lógica y Conjuntos 1"', 'active' => 'yes', 'item_id' => null, 'order' => 2, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-valor-abs-desigualdades-3',       'name' => 'Guía "Cálculo: Valor Absoluto y Desigualdades"', 'active' => 'yes', 'item_id' => null, 'order' => 3, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-funciones-4',                     'name' => 'Guía "Cálculo: Funciones"', 'active' => 'yes', 'item_id' => null, 'order' => 4, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-sumatoria-5',                'name' => 'Guía "Complementos: Sumatorias 1"', 'active' => 'yes', 'item_id' => null, 'order' => 5, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-mix-nr-6',                        'name' => 'Guía "Cálculo: Mix Números Reales"', 'active' => 'yes', 'item_id' => null, 'order' => 6, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-logica-7',                   'name' => 'Guía "Complementos: Lógica 1"', 'active' => 'yes', 'item_id' => null, 'order' => 7, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-conjuntos-8',                'name' => 'Guía "Complementos: Conjuntos 1"', 'active' => 'yes', 'item_id' => null, 'order' => 8, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-complementos-otros-logica-conjuntos-9',   'name' => 'Guía "Complementos: Lógica y Conjuntos 2"', 'active' => 'yes', 'item_id' => null, 'order' => 9, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-complementos-otros-sumatorias-10',        'name' => 'Guía "Complementos: Sumatorias 2"', 'active' => 'yes', 'item_id' => null, 'order' => 10, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-3-complementos-otros-sumatorias-11',        'name' => 'Guía "Complementos: Sumatorias 3"', 'active' => 'yes', 'item_id' => null, 'order' => 11, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-progresiones-12',            'name' => 'Guía "Complementos: Progresiones"', 'active' => 'yes', 'item_id' => null, 'order' => 12, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-limites-13',                      'name' => 'Guía "Cálculo: Límites 1"', 'active' => 'yes', 'item_id' => null, 'order' => 13, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-calculo-limites-14',                      'name' => 'Guía "Cálculo: Límites 2"', 'active' => 'yes', 'item_id' => null, 'order' => 14, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-trigonometria-15',           'name' => 'Guía "Complementos: Trigonometría 1"', 'active' => 'yes', 'item_id' => null, 'order' => 15, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-complementos-trigonometria-16',           'name' => 'Guía "Complementos: Trigonometría 2"', 'active' => 'yes', 'item_id' => null, 'order' => 16, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-3-complementos-trigonometria-17',           'name' => 'Guía "Complementos: Trigonometría 3"', 'active' => 'yes', 'item_id' => null, 'order' => 17, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complementos-geo-analitica-18',           'name' => 'Guía "Complementos: Geometría Analítica"', 'active' => 'yes', 'item_id' => null, 'order' => 18, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-1-usm-19',                  'name' => 'Guía "Cálculo: Clase 1 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 19, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-2-usm-20',                  'name' => 'Guía "Cálculo: Clase 2 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 20, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-3-usm-21',                  'name' => 'Guía "Cálculo: Clase 3 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 21, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-4-usm-22',                  'name' => 'Guía "Cálculo: Clase 4 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 22, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-5-usm-23',                  'name' => 'Guía "Cálculo: Clase 5 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 23, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-1-usm-24',              'name' => 'Guía "Complementos: Clase 1 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 24, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-2-usm-25',              'name' => 'Guía "Complementos: Clase 2 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 25, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-3-usm-26',              'name' => 'Guía "Complementos: Clase 3 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 26, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-4-usm-27',              'name' => 'Guía "Complementos: Clase 4 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 27, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-5-usm-28',              'name' => 'Guía "Complementos: Clase 5 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 28, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-6-usm-29',              'name' => 'Guía "Complementos: Clase 6 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 29, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-6-usm-30',                  'name' => 'Guía "Cálculo: Clase 6 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 30, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-7-usm-31',                  'name' => 'Guía "Cálculo: Clase 7 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 31, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-8-usm-32',                  'name' => 'Guía "Cálculo: Clase 8 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 32, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-9-usm-33',                  'name' => 'Guía "Cálculo: Clase 9 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 33, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-10-usm-34',                 'name' => 'Guía "Cálculo: Clase 10 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 34, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-11-usm-35',                 'name' => 'Guía "Cálculo: Clase 11 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 35, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-clase-12-usm-36',                 'name' => 'Guía "Cálculo: Clase 12 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 36, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-7-1-usm-37',            'name' => 'Guía "Complementos: Clase 7-1 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 37, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-7-2-usm-38',            'name' => 'Guía "Complementos: Clase 7-2 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 38, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-8-usm-39',              'name' => 'Guía "Complementos: Clase 8 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 39, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-clase-9-usm-40',              'name' => 'Guía "Complementos: Clase 9 USM"', 'active' => 'yes', 'item_id' => null, 'order' => 40, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-num-complejos-41',            'name' => 'Guía "Complementos: Números Complejos"', 'active' => 'yes', 'item_id' => null, 'order' => 41, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-complemento-num-complejos-42',            'name' => 'Guía "Complementos: Números Complejos 2"', 'active' => 'yes', 'item_id' => null, 'order' => 42, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-polinomios-43',               'name' => 'Guía "Complementos: Polinomios"', 'active' => 'yes', 'item_id' => null, 'order' => 43, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-3-calculo-limites-44',                      'name' => 'Guía "Cálculo: Límites 3"', 'active' => 'yes', 'item_id' => null, 'order' => 44, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-derivadas-45',                    'name' => 'Guía "Cálculo: Derivadas 1"', 'active' => 'yes', 'item_id' => null, 'order' => 45, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-calculo-derivadas-46',                    'name' => 'Guía "Cálculo: Derivadas 2"', 'active' => 'yes', 'item_id' => null, 'order' => 46, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-3-calculo-derivadas-max-min-47',            'name' => 'Guía "Cálculo: Derivadas 3 (Máximos y Mínimos)"', 'active' => 'yes', 'item_id' => null, 'order' => 47, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-4-calculo-derivadas-48',                    'name' => 'Guía "Cálculo: Derivadas 4"', 'active' => 'yes', 'item_id' => null, 'order' => 48, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-2-complemento-polinomios-49',               'name' => 'Guía "Complementos: Polinomios 2"', 'active' => 'yes', 'item_id' => null, 'order' => 49, 'parent_id' => null], */

            //GRUPO 2 Octubre 2024

            /* ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-calculo-continuidad-50',               'name' => 'Guía "Cálculo: Continuidad"', 'active' => 'yes', 'item_id' => null, 'order' => 50, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 3, 'semester_id' => null, 'slug' => 'chile-utfsm-mat021-guia-1-complemento-induccion-51',               'name' => 'Guía "Complementos: Inducción"', 'active' => 'yes', 'item_id' => null, 'order' => 51, 'parent_id' => null], */

            //CERTAMENES

             /* ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 39, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2005', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 37, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2006', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 37, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2006', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 37, 'slug' => 'chile-utfsm-mat021-certamen-3-1er-semestre-2006', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 37, 'slug' => 'chile-utfsm-mat021-certamen-rec-1er-semestre-2006', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //5
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 37, 'slug' => 'chile-utfsm-mat021-certamen-ex-1er-semestre-2006', 'certamen_number' => '0', 'name' => 'Exámen', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 38, 'slug' => 'chile-utfsm-mat021-certamen-1-2do-semestre-2006', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 38, 'slug' => 'chile-utfsm-mat021-certamen-ex-2do-semestre-2006', 'certamen_number' => '0', 'name' => 'Exámen', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 35, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2007', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 35, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2007', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //10
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 35, 'slug' => 'chile-utfsm-mat021-certamen-3-1er-semestre-2007', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 35, 'slug' => 'chile-utfsm-mat021-certamen-rec-1er-semestre-2007', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 35, 'slug' => 'chile-utfsm-mat021-certamen-ex-1er-semestre-2007', 'certamen_number' => '0', 'name' => 'Exámen', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 36, 'slug' => 'chile-utfsm-mat021-certamen-1-2do-semestre-2007', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 36, 'slug' => 'chile-utfsm-mat021-certamen-2-2do-semestre-2007', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //15
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 36, 'slug' => 'chile-utfsm-mat021-certamen-3-2do-semestre-2007', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 36, 'slug' => 'chile-utfsm-mat021-certamen-rec-2do-semestre-2007', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 33, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2008', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 33, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2008', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 33, 'slug' => 'chile-utfsm-mat021-certamen-3-1er-semestre-2008', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //20
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 33, 'slug' => 'chile-utfsm-mat021-certamen-rec-1er-semestre-2008', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 34, 'slug' => 'chile-utfsm-mat021-certamen-1-2do-semestre-2008', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 34, 'slug' => 'chile-utfsm-mat021-certamen-2-2do-semestre-2008', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 34, 'slug' => 'chile-utfsm-mat021-certamen-3-2do-semestre-2008', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 34, 'slug' => 'chile-utfsm-mat021-certamen-rec-2do-semestre-2008', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //25
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 31, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2009', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 31, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2009', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 31, 'slug' => 'chile-utfsm-mat021-certamen-3-1er-semestre-2009', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 31, 'slug' => 'chile-utfsm-mat021-certamen-rec-1er-semestre-2009', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 32, 'slug' => 'chile-utfsm-mat021-certamen-1-2do-semestre-2009', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //30
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 32, 'slug' => 'chile-utfsm-mat021-certamen-2-2do-semestre-2009', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 32, 'slug' => 'chile-utfsm-mat021-certamen-3-2do-semestre-2009', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 32, 'slug' => 'chile-utfsm-mat021-certamen-rec-2do-semestre-2009', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 1, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2010', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 1, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2010', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //35
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 1, 'slug' => 'chile-utfsm-mat021-certamen-3-1er-semestre-2010', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 1, 'slug' => 'chile-utfsm-mat021-certamen-rec-1er-semestre-2010', 'certamen_number' => '0', 'name' => 'Certámen Recuperativo', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 2, 'slug' => 'chile-utfsm-mat021-certamen-1-2do-semestre-2010', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 2, 'slug' => 'chile-utfsm-mat021-certamen-2-2do-semestre-2010', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 2, 'slug' => 'chile-utfsm-mat021-certamen-3-2do-semestre-2010', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            //40
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 3, 'slug' => 'chile-utfsm-mat021-certamen-1-1er-semestre-2011', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 3, 'slug' => 'chile-utfsm-mat021-certamen-2-1er-semestre-2011', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null], */

            //GRUPO CERTAMENES MAT021 OCTUBRE 2024 (PARENT_ID del 43 al 93)

            //43 - 61 CERTAMENES 1 MAT021
            /* ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2013', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2013', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2014', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2014-2', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2014', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2014-2', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2015', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2015', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2016', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2016', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 15, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2017', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 16, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2017', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 18, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2018', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 19, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2019', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2022', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 26, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2022', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2023', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 28, 'slug' => 'chile-utfsm-mat021-certamen-1-2-semestre-2023', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 29, 'slug' => 'chile-utfsm-mat021-certamen-1-1-semestre-2024', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],

            //62 - 77 CERTAMENES 1 MAT021
             ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 6, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2012', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
             ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2013', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
             ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2013', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
             ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2014', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2014', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2016', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2016', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 15, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2017', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 16, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2017', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 17, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2018', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2022', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 26, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2022', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat021-certamen-2-1-semestre-2023', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 28, 'slug' => 'chile-utfsm-mat021-certamen-2-2-semestre-2023', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],

            //78 - 93 CERTAMENES 1 MAT021
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2013', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2013-2', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2013-3', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2013', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2014', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2014', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2014-2', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2015', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2016', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2016', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 15, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2017', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 18, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2018', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 19, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2019', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2022', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 26, 'slug' => 'chile-utfsm-mat021-certamen-3-2-semestre-2022', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 1, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat021-certamen-3-1-semestre-2023', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null], */

            //1-15 CERTAMENES 1,2 y 3 MAT022
            /*  ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 15, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2017', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 16, 'slug' => 'chile-utfsm-mat022-certamen-1-2-semestre-2017', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 20, 'slug' => 'chile-utfsm-mat022-certamen-1-2-semestre-2019', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2022', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2023', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 15, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2017', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 16, 'slug' => 'chile-utfsm-mat022-certamen-2-2-semestre-2017', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2022', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 26, 'slug' => 'chile-utfsm-mat022-certamen-2-2-semestre-2022', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2023', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 16, 'slug' => 'chile-utfsm-mat022-certamen-3-2-semestre-2017', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 18, 'slug' => 'chile-utfsm-mat022-certamen-3-2-semestre-2018', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 25, 'slug' => 'chile-utfsm-mat022-certamen-3-1-semestre-2022', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 26, 'slug' => 'chile-utfsm-mat022-certamen-3-2-semestre-2022', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 27, 'slug' => 'chile-utfsm-mat022-certamen-3-1-semestre-2023', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null], */

            //16-38 CERTAMENES 1,2 y 3 MAT022

            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2013', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat022-certamen-1-2-semestre-2013', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2014', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat022-certamen-1-2-semestre-2014', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2015', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat022-certamen-1a-2-semestre-2015', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat022-certamen-1b-2-semestre-2015', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat022-certamen-1-1-semestre-2016', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat022-certamen-1-2-semestre-2016', 'certamen_number' => '1', 'name' => 'Certámen 1', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],

            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2013', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat022-certamen-2-2-semestre-2013', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2014', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 10, 'slug' => 'chile-utfsm-mat022-certamen-2-2-semestre-2014', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat022-certamen-2a-1-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 11, 'slug' => 'chile-utfsm-mat022-certamen-2b-1-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat022-certamen-2a-2-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 12, 'slug' => 'chile-utfsm-mat022-certamen-2b-2-semestre-2015', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat022-certamen-2-1-semestre-2016', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat022-certamen-2-2-semestre-2016', 'certamen_number' => '2', 'name' => 'Certámen 2', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],

            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 7, 'slug' => 'chile-utfsm-mat022-certamen-3-1-semestre-2013', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 8, 'slug' => 'chile-utfsm-mat022-certamen-3-2-semestre-2013', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 9, 'slug' => 'chile-utfsm-mat022-certamen-3-1-semestre-2014', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 13, 'slug' => 'chile-utfsm-mat022-certamen-3-1-semestre-2016', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
            ['university_id' => 1, 'subject_id' => 2, 'type_id' => 1, 'semester_id' => 14, 'slug' => 'chile-utfsm-mat022-certamen-3-2-semestre-2016', 'certamen_number' => '3', 'name' => 'Certámen 3', 'active' => 'yes', 'item_id' => null, 'order' => 1, 'parent_id' => null],
 
        ];

        foreach ($data as $exercise) {
            ExerciseUniversity::create($exercise);
        }
        Log::info('Seeding ExerciseUniversities completed', ['total_records' => count($data)]);
    }
    
}
